# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Grind
email: Chris@genesis-webdesign.com
description: > # this means to ignore newlines until "baseurl:"
  I write about things I am learning in the Front-end Development world and thoughts on my mind about the industry.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chriswiley.github.io" # the base hostname & protocol for your site
twitter_username: oldsage_fl
github_username:  chriswiley

# Build settings
markdown: kramdown
